name = "OpenSSLGroups"
uuid = "50771dd1-78b8-490c-a786-5ddc80ce15da"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.1.1"

[deps]
CryptoGroups = "bc997328-bedd-407e-bcd3-5758e064a52d"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"

[compat]
CryptoGroups = "0.6"
InteractiveUtils = "1.11"
OpenSSL_jll = "3.0.15"
julia = "1.10"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ShuffleProofs = "31a120cc-b3cb-4d07-bbdb-d498660ddfd8"
SigmaProofs = "f8559b4c-f045-44a2-8db2-503e40bb7416"

[targets]
test = ["Test", "SafeTestsets", "InteractiveUtils", "ShuffleProofs", "SigmaProofs"]
