name = "OpenSSLGroups"
uuid = "50771dd1-78b8-490c-a786-5ddc80ce15da"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.1.0"

[deps]
CryptoGroups = "bc997328-bedd-407e-bcd3-5758e064a52d"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"

[compat]
CryptoGroups = "0.5.0"
Libdl = "1.11.0"
OpenSSL_jll = "3.0.15"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]